apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-java-helm.fullname" . }}
  labels:
    {{- include "simple-java-helm.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "simple-java-helm.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "simple-java-helm.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: simple-java-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}

           resources:
             requests:
               cpu: "100m"
               memory: "128Mi"
             limits:
               cpu: "500m"
               memory: "256Mi"

